#!/bin/sh
export CUDA_VISIBLE_DEVICES="0"
export HOME=/scratch
export CC_DIR=/home/cryocore/git/CryoCloud
cd /home/cryocore/git/CryoniteOil/
export PATH=/home/cryocore/git/CryoCloud/bin:$PATH
export PYTHONPATH=/home/cryocore/git/CryoCore:/home/cryocore/git/CryoCloud:.:/home/cryocore/git/oilspill_segmentation_v2/:./modules:/home/cryocore/git/CryoCloud/Modules
ccnode $@

